---
kind: pipeline
type: docker
name: snapshot-publish

trigger:
  branch:
    - develop

volumes:
  - name: m2
    host:
      path: /drone/volume/m2

steps:

  - name: publish
    image: maven:3.8.5-openjdk-17
    privileged: true
    volumes:
      - name: m2
        path: /root/.m2/repository
    environment:
      MAVEN_SETTINGS:
        from_secret: MAVEN_SETTINGS
    commands:
      - echo "$MAVEN_SETTINGS" >> maven-settings.xml
      - mvn --settings maven-settings.xml -U -P snapshot clean deploy

---
kind: pipeline
type: docker
name: release-maven-central

trigger:
  ref:
    - refs/tags/v.*.*.*

volumes:
  - name: m2
    host:
      path: /drone/volume/m2

steps:

  - name: publish maven central
    image: maven:3.8.5-openjdk-17
    privileged: true
    volumes:
      - name: m2
        path: /root/.m2/repository
    environment:
      GPG_PRIVATE_KEY:
        from_secret: GPG_PRIVATE_KEY
      MAVEN_SETTINGS:
        from_secret: MAVEN_SETTINGS
      GPG_PASSPHRASE:
        from_secret: GPG_PASSPHRASE
    commands:
      - echo "$GPG_PRIVATE_KEY" >> gpg.key
      - echo "$MAVEN_SETTINGS" >> maven-settings.xml
      - gpg --pinentry-mode loopback --passphrase $GPG_PASSPHRASE --import gpg.key
      - mvn --settings maven-settings.xml -U -P ossrh,release clean deploy

---
kind: pipeline
type: docker
name: release-struchkov-nexus

trigger:
  ref:
    - refs/tags/v.*.*.*

volumes:
  - name: m2
    host:
      path: /drone/volume/m2

steps:

  - name: publish struchkov nexus
    image: maven:3.8.5-openjdk-17
    privileged: true
    volumes:
      - name: m2
        path: /root/.m2/repository
    environment:
      GPG_PRIVATE_KEY:
        from_secret: GPG_PRIVATE_KEY
      MAVEN_SETTINGS:
        from_secret: MAVEN_SETTINGS
      GPG_PASSPHRASE:
        from_secret: GPG_PASSPHRASE
    commands:
      - echo "$GPG_PRIVATE_KEY" >> gpg.key
      - echo "$MAVEN_SETTINGS" >> maven-settings.xml
      - gpg --pinentry-mode loopback --passphrase $GPG_PASSPHRASE --import gpg.key
      - mvn --settings maven-settings.xml -U -P ossrh,release-struchkov-nexus clean deploy

---
kind: pipeline
type: docker
name: create-docs-site

trigger:
  branch:
    - develop

steps:
  - name: build site
    image: upagge/mkdocs-material
    commands:
      - mkdocs gh-deploy --force
---
kind: signature
hmac: 3e4badb68ae8e0fc102b948d3383ca67155ad0e733bbbdb43560862c5de4fdd6

...
