site_name: GodFather Telegram

repo_url: https://github.com/Godfather-Bots/telegram-bot
repo_name: Godfather-Bots/telegram-bot
#edit_uri: edit/master/documentation/docs

nav:
  - 'index.md'

theme:
  name: material
  language: ru
  favicon: assets/favicon.ico
  icon:
    logo: simple/telegram
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: light blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - search
    - search.suggest
    - search.highlight
    - content.action.edit
    - toc.follow
  plugins:
    - meta
    - tags
    - social
    - blog:
        blog_dir: ./blog
    - search:
        lang: ru
    - git-revision-date-localized:
        enable_creation_date: true
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
      title: Содержание

extra:
  generator: false
  version:
    provider: mike
#  alternate:
#    - name: Русский
#      link: /ru/
#      lang: ru